
apiVersion: v1
kind: Pod
metadata:
   name:  configmapexample-volume
spec:
   containers:
     - name:  configmapexample-volume
       image: busybox
       command:  [ "/bin/sh", "-c", "ls /etc/custom_config ; cat /etc/custom_config/customkey1 ; ls /etc/secret; cat /etc/secret/key1; tail -f /etc/hosts -n 0"]
       volumeMounts:
       - name: config-volume
         mountPath: /etc/custom_config
       - name: secret-volume
         mountPath: /etc/secret
         readOnly: true
       imagePullPolicy: IfNotPresent
   volumes:
    - name: config-volume
      configMap:
        name: custom-config
    - name: secret-volume
      secret:
        secretName: my-secret